<a href="https://colab.research.google.com/github/sateesh12/deep_learning_basics/blob/master/Tensors_Basic_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Author : Sateesh
# Date  : 18/June/2020
#Purpose : Simple operations of tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.2.0


In [ ]:
#Create a tensor
rank_0 = tf.constant(94)
print(rank_0)

tf.Tensor(94, shape=(), dtype=int32)


In [ ]:
#Rank-1 tensor
rank_1_1 = tf.constant([1,2,3])
print(rank_1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
#Rank-1 another tensor
rank_1_2 = tf.constant([4,5,6])
print(rank_1_2)

tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [ ]:
rank_1_3 = rank_1_1 + rank_1_2
print(rank_1_3)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
m1 = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(m1)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
m2 = tf.constant([[1,0,0],
                  [0,1,0],
                  [0,0,1]])
print(m2)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [ ]:
m3 = m1 + m2
print(m3)

tf.Tensor(
[[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]], shape=(3, 3), dtype=int32)


In [ ]:
m4 = m1 - m2
print(m4)

tf.Tensor(
[[0 2 3]
 [4 4 6]
 [7 8 8]], shape=(3, 3), dtype=int32)


In [ ]:
m7 = tf.constant([[1,1,1],
                  [0,0,0],
                  [0,0,0]])
print(m7)

m5 = m1 * m7
print(m5)

tf.Tensor(
[[1 1 1]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [ ]:
m6 = tf.matmul(m1,m2)
print(m6)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
